[package]
description = "Ethcore utility library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-util"
version = "1.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethcore-bigint = { path = "bigint", features = ["heapsizeof"] }
hashdb = { path = "hashdb" }
memorydb = { path = "memorydb" }

[dev-dependencies]
ethcore-bytes = { path = "bytes" }
keccak-hash = { path = "hash" }
log = "0.3"
patricia-trie = { path = "patricia_trie" }
triehash = { path = "triehash" }
