[package]
description = "Large fixed-size integers and hash function outputs"
homepage = "http://parity.io"
repository = "https://github.com/paritytech/parity"
license = "MIT/Apache-2.0"
name = "ethcore-bigint"
version = "0.1.3"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
bigint = "1.0.4"
rustc-serialize = "0.3"
heapsize = "0.3"
rand = "0.3.12"
libc = "0.2"

[features]
x64asm_arithmetic=[]
rust_arithmetic=[]
