[package]
name = "hashdb"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "trait for hash-keyed databases."
license = "GPL-3.0"

[dependencies]
elastic-array = "0.9"
ethcore-bigint = { version = "0.1.3", path = "../bigint" }
